package cn.com.gome.dujia.ws.client.sap.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_IFI02_REQ", targetNamespace = "URN:EC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIIFI02REQ {


    /**
     * 
     * @param parameters
     * @return
     *     returns cn.com.gome.showticket.ws.sap.receipt.client.ZECSDAYSACCResponse
     */
    @WebMethod(operationName = "SI_IFI02_REQ", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZEC_S_DAYS_ACC.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZECSDAYSACCResponse siIFI02REQ(
        @WebParam(name = "ZEC_S_DAYS_ACC", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
        ZECSDAYSACC parameters);

}
