package cn.com.gome.dujia.ws.client.sap.income;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XI_9928cfb4f5b637869e84d4a5dc5e47a6_Service", targetNamespace = "URN:XUNI", wsdlLocation = "file:/D:/BS_XUNI_SI_XUNI2ECC_IFI402_VirtualBusinessIncome_REQ.wsdl")
public class XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service
    extends Service
{

    private final static URL XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_WSDL_LOCATION;
    
    private final static WebServiceException XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_EXCEPTION;
    
    private final static QName XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_QNAME = new QName("URN:XUNI", "XI_9928cfb4f5b637869e84d4a5dc5e47a6_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/BS_XUNI_SI_XUNI2ECC_IFI402_VirtualBusinessIncome_REQ.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_WSDL_LOCATION = url;
        XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_EXCEPTION = e;
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service() {
        super(__getWsdlLocation(), XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_QNAME);
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_QNAME, features);
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service(URL wsdlLocation) {
        super(wsdlLocation, XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_QNAME);
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_QNAME, features);
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XI9928Cfb4F5B637869E84D4A5Dc5E47A6Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIXUNI2ECCIFI402VirtualBusinessIncomeREQ
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIXUNI2ECCIFI402VirtualBusinessIncomeREQ getHTTPPort() {
        return super.getPort(new QName("URN:XUNI", "HTTP_Port"), SIXUNI2ECCIFI402VirtualBusinessIncomeREQ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIXUNI2ECCIFI402VirtualBusinessIncomeREQ
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIXUNI2ECCIFI402VirtualBusinessIncomeREQ getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("URN:XUNI", "HTTP_Port"), SIXUNI2ECCIFI402VirtualBusinessIncomeREQ.class, features);
    }

    /**
     * 
     * @return
     *     returns SIXUNI2ECCIFI402VirtualBusinessIncomeREQ
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIXUNI2ECCIFI402VirtualBusinessIncomeREQ getHTTPSPort() {
        return super.getPort(new QName("URN:XUNI", "HTTPS_Port"), SIXUNI2ECCIFI402VirtualBusinessIncomeREQ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIXUNI2ECCIFI402VirtualBusinessIncomeREQ
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIXUNI2ECCIFI402VirtualBusinessIncomeREQ getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("URN:XUNI", "HTTPS_Port"), SIXUNI2ECCIFI402VirtualBusinessIncomeREQ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_EXCEPTION!= null) {
            throw XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_EXCEPTION;
        }
        return XI9928CFB4F5B637869E84D4A5DC5E47A6SERVICE_WSDL_LOCATION;
    }

}
