package cn.com.gome.dujia.ws.client.rb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AcceptRefundTask", targetNamespace = "http://webservice.rb.gome.founder.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AcceptRefundTask {


    /**
     * 
     * @param taskBean
     * @return
     *     returns cn.com.gome.train.ws.rb.refund.client.RefundTaskReply
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "acceptTask", targetNamespace = "http://webservice.rb.gome.founder.com/", className = "cn.com.gome.dujia.ws.client.rb.AcceptTask")
    @ResponseWrapper(localName = "acceptTaskResponse", targetNamespace = "http://webservice.rb.gome.founder.com/", className = "cn.com.gome.dujia.ws.client.rb.AcceptTaskResponse")
    public RefundTaskReply acceptTask( @WebParam(name = "taskBean", targetNamespace = "")RefundBankTask taskBean);
}
